# Copyright 2026 DragonWork
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    versioning-strategy: increase
    schedule:
      interval: daily
    commit-message:
      prefix: build(deps)
    cooldown:
      semver-patch-days: 1
      semver-minor-days: 3
      semver-major-days: 5
    groups:
      compatible-cargo-updates:
        patterns: ['*']
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
    cooldown:
      default-days: 3
    groups:
      actions:
        patterns: ['*']
